AMproject/AMproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('sub1/', include('sub1app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #url/media로 접근 가능하도록

AMproject/mainapp/urls.py
from django.urls import path 
from . import views

app_name = 'mainapp'
urlpatterns = [
    path('', views.main, name='main'), #main
    path('go_search/', views.go_search, name="go_search"),
    path('search_result/', views.search_result, name='search_result'),
]

AMproject/sub1app/urls.py
from django.urls import path 
from . import views

app_name = 'sub1app'
urlpatterns = [
    path('', views.searchRC, name='searchRC'),
    path('center_info/<int:obj_pk>', views.center_info, name='center_info'),
    path('rescue/', views.rescue, name='rescue'),
]

AMproject/mainapp/models.py
from django.db import models

# Create your models here.

#사진을 저장할 수 있게
class box_image(models.Model):
    image=models.ImageField(upload_to='userimg', null=True)

    def __str__(self):
        return f'{self.pk} : {self.image}'

    def delete(self, *args, **kwargs):
        #삭제할때 미디어 파일도 자동으로 삭제
        super(box_image, self).delete(*args, **kwargs)
        if self.image : 
            os.remove(os.path.join(settings.MEDIA_ROOT, self.image.path))

class Info(models.Model):
    name = models.CharField(max_length=50)
    explain = models.TextField(null=True)
    endangered = models.BooleanField(default=False)#멸종위기종여부
    protected = models.BooleanField(default=False) #보호종여부
    etc = models.TextField(null=True)

    def __str__(self):
        return f'{self.pk} : {self.name}'

AMproject/sub1app/models.py
from django.db import models
# from django.db.models import Model
# Create your models here.

class RescueCenter(models.Model):
    name = models.CharField(max_length=30)
    address_road = models.CharField(max_length=50)
    address_parcdel = models.CharField(max_length=50, null=True)
    latitude = models.CharField(max_length=50, null=True)
    longitude = models.CharField(max_length=50, null=True)
    opentime = models.CharField(max_length=30)
    closetime = models.CharField(max_length=30)
    dayoff = models.CharField(max_length=30, null=True)
    designated = models.DateField(null=True, )
    area = models.TextField(null=True)
    num_Vet = models.IntegerField(null=True)
    num_Researcher = models.IntegerField(null=True)
    room_consulation = models.IntegerField(null=True)
    room_operating = models.IntegerField(null=True)
    room_image = models.IntegerField(null=True)
    room_hospital = models.IntegerField(null=True)
    room_genetic = models.IntegerField(null=True)
    room_remedical = models.IntegerField(null=True)
    room_isolated = models.IntegerField(null=True)
    num_vehicle = models.IntegerField(null=True)
    box	= models.TextField(null=True)
    equipment_trep = models.TextField(null=True)
    equipment_medical = models.TextField(null=True)
    explain	= models.TextField(null=True)
    representative = models.TextField(null=True)
    tel = models.CharField(max_length = 30)
    XXX = models.CharField(max_length=30)
    def __str__(self):
        return f'{self.pk} : {self.name}'


class AnimalInfo(models.Model):
    animal_class = models.CharField(max_length=50)#강
    infoNum = models.CharField(max_length=50)#접수번호
    name = models.CharField(max_length=50)#국명
    natural = models.CharField(max_length=50) #천연기념물여부
    endangered = models.CharField(max_length=50)#멸종위기종여부
    date_rescue = models.DateField()#구조일자
    date_result = models.DateField()#구조결과일자
    result = models.CharField(max_length=50)#구조결과
    discoverd_place = models.CharField(max_length=50)#발견장소

    def __str__(self):
            return f'{self.pk} - 접수번호 : {self.infoNum}, {self.name}'

AMproject/mainapp/views.py
from django.shortcuts import render, redirect
# from django.views.decorators.http import require_GET, require_POST
from .models import box_image, Info
from yolo_object_detection.yolo_detection import result_str 

# Create your views here.

def main(request):
    return render(request, 'mainapp/main.html')

def go_search(request):
    return render(request, 'mainapp/go_search.html')

# @require_POST
def search_result(request):
    context={}
    
    if request.method == 'POST':
        if 'image' in request.FILES:
            imagee=request.FILES['image']
            new_image=box_image(image = imagee)
            new_image.save()
            fname = imagee.name
            file_path = f"./media/userimg/{fname}"
            context['file_path'] = file_path

            #결과값 받아오기
            what = result_str(file_path)
            if (what != "찾을 수 없습니다."):
                context['what'] = what + "입니다."
            else:
                context['what'] = what
            
            #사용후 파일 지우기
            #new_image.delete()

            # 동물정보 표시
            try:
                infodata = Info.objects.get(name = what)
            except:
                infodata = None
            print(infodata)
            context['infodata'] = infodata

            return render (request, 'mainapp/search_result.html', context)

        else:
            #이미지가 업로드 되지 않으면 다시 화면 보여줌
            redirect('mainapp:go_search')

        
    else :
        #get 요청(잘못된요청) -> main 페이지로
        return redirect('mainapp:main')
    

AMproject/sub1app/views.py
from django.shortcuts import render, redirect
from .models import RescueCenter, AnimalInfo
from django.core.paginator import Paginator
# Create your views here.

def searchRC(request):

    context = {}
    page = request.GET.get('page', 1) #페이지 디폴트 값1

    contents = RescueCenter.objects.all()
    if request.method == "POST":
        #검색한다
        
        regions = request.POST.getlist('regions[]')
        #regions  ['전체', '서울', '전남']
        print(regions)
        if '전체' in regions : 
            context['results'] = contents
            context['regions'] = ["전체"]
            return render(request, 'sub1app/searchRc.html', context)

        else :
            #지역 검색
            results = contents.filter(XXX='임시')
            for reg in regions:
                temp = contents.filter(XXX=reg)
                results  = results.union(temp)
            context['results'] = results
            context['regions'] = regions
            return render(request, 'sub1app/searchRc.html', context)

    else :
        #전체 리스트 보여주기
        paginator = Paginator(contents, 10)#페이지 당 10개씩
        page_obj = paginator.get_page(page)
        context['results'] = page_obj
        context['regions'] = ["전체"]
        return render(request, 'sub1app/searchRc.html', context)


def center_info(request, obj_pk):
    context={}

    contents = RescueCenter.objects.get(pk=obj_pk)
    context['data'] = contents

    return render(request, 'sub1app/center_info.html', context)

def rescue(request):
    context={}

    contents = AnimalInfo.objects.all().order_by('-date_result', '-date_rescue')
    page = request.GET.get('page', 1) #페이지 디폴트 값1
    paginator = Paginator(contents, 6)
    page_obj = paginator.get_page(page)

    context['data'] = page_obj

    return render(request,'sub1app/rescue.html', context)

AMproject/mainapp/templates/mainapp/go_search.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'mainapp/go_search.css' %}"  type='text/css'> 
{% endblock %}

{% block content %}
<h2>이미지 검색</h2>
<form action="{% url 'mainapp:search_result' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div id="imgform">
        <input type="file" name="image" id='files'><br>
        <div class="thumbnail">
            <img id="image" style="width: 200px;"/>
        </div>
        <input id="img_search_btn" type="submit" value="검색">
    </div>
</form>
    
<script>
    document.getElementById("files").onchange = function () {
    var reader = new FileReader();

    reader.onload = function (e) {
        // get loaded data and render thumbnail.
        document.getElementById("image").src = e.target.result;
    };

    // read the image file as a data URL.
    reader.readAsDataURL(this.files[0]);
};
</script>
    
{% endblock %}

AMproject/mainapp/templates/mainapp/main.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'mainapp/main.css' %}"  type='text/css'> 
{% endblock %}

{% block content %}
    <div class="button_list"> 
        <div class="menu" id="no1"><a href="{% url 'mainapp:go_search' %}"><b>야생동물검색</b></a></div>
        <div class="menu" id="no2"><a href="{% url 'sub1app:searchRC' %}"><b>구조센터 찾기</b></a></div>
        <div class="menu" id="no3" ><a href="{% url 'sub1app:rescue' %}"><b>구조동물 정보 열람</b></a></div>
    </div>
{% endblock %}

AMproject/mainapp/templates/mainapp/search_result.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'mainapp/search_result.css' %}"  type='text/css'> 
{% endblock %}

{% block content %}
<h2>이미지 검색 결과</h2>
<div class="result_info">
    <div class="image_box" >
        <img src="../../{{ file_path }}" alt="" style="width:200px; height:200px;">
    </div>
    <h3 id="objresult">{{ what }}</h3>
    <div class="explain">
        {% if infodata %}
        <div class = "infos">
            {% if infodata.endangered %}
            <span>멸종 위기 동물입니다.</span>
            {% elif infodata.protected %}
            <span>보호종입니다.</span>
            {% endif %}
            <span id="small">{{infodata.explain}}
                {{infodata.etc}}</span>
        </div>
        {% else %}
        <div>
            정보가 없습니다.
        </div>
        {% endif %}
    </div>
    <a id="go_rc" href="{% url 'sub1app:searchRC' %}">근처 구조센터 찾기</a>
</div>
{% endblock %}

AMproject/sub1app/templates/sub1app/center_info.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'sub1app/center_info.css' %}"  type='text/css'> 
{% endblock %}

{% block content %}
    
    <h2>{{data.name}}</h2>
    <ul>
        <li><b class="b_opt">주소 </b>: {{data.address_road}}</li>
        <li><b class="b_opt">운영시간 </b>: {{data.opentime}} ~ {{data.cloasetime}}</li>
        <li><b class="b_opt">휴무일 </b>: {{data.dayoff}}</li>
        <li><b class="b_opt">전화번호 </b>: {{data.tel}}</li>
        <li><b class="b_opt">대표자 </b>: {{data.representative}}</li>
        <li>{{data.explain}}</li>
    </ul>
    <table>
        <tr>
            <td class="tdh"><B>운반상자현황</B></td>
            <td>{{ data.box }}</td>
        </tr>
        <tr>
            <td class="tdh"><B>포획장비현황</B></td>
            <td>{{ data.equipment_trep }} </td>
        </tr>
        <tr>
            <td class="tdh"><B>진료장비현황</B></td>
            <td>{{ data.equipment_medical}}</td>
        </tr>
    </table>
    <table class="nlist">
        <thead>
        <tr>
            <td><B>수의사</B></td>
            <td><B>질병연구자</B></td>
            <td><B>진료실</B></td>
            <td><B>수술실</B></td>
            <td><B>영상진단실</B></td>
            <td><B>입원실</B></td>
        </thead>
        <tbody>
        <tr>
            <td>{{data.num_Vet}}</td>
            <td>{{data.num_Researcher}}</td>
            <td>{{data.room_consulation}}</td>
            <td>{{data.room_operating}}</td>
            <td>{{data.room_image}}</td>
            <td>{{data.room_hospital}}</td>
        </tr>
        <tbody>
    </table>
    <table>
        <thead>
            <tr>
                <td><B>유전자원보관실</B></td>
                <td><B>재활실</B></td>
                <td><B>격리실</B></td>
                <td><B>구조차량</B></td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{data.room_genetic}}</td>
                <td>{{data.room_remedical}}</td>
                <td>{{data.room_isolated}}</td>
                <td>{{data.num_vehicle}}</td>
            </tr>
        <tbody>    
    </table>
        
    
        
    
{% endblock %}

AMproject/sub1app/templates/sub1app/rescue.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'sub1app/rescue.css' %}"  type='text/css'> 
{% endblock %}

{% block content %}
    <h2>구조 동물 정보 열람</h2>
    <div class="container">
        {% for datum in data %}
        <div class="inbox">
            <span><b>강</b> : {{datum.animal_class}}<br></span>
            <span><b>접수번호</b> : {{datum.infoNum}}<br></span>
            <span><b>국 명</b> : {{datum.name}}<br></span>
            <span><b>천연기념물</b> : {{datum.natural}}<br></span>
            <span><b>멸종위기종</b> : {{datum.endangered}}<br></span>
            <span><b>구조결과</b> : {{datum.result}}<br></span>
            <span><b>발견장소</b> : {{datum.discoverd_place}}<br></span>
            <span><b>구조일자</b> : {{datum.date_rescue}}<br></span>
            <span><b>구조결과일자</b> : {{datum.date_result}}<br></span>
        </div>
        {% endfor %}
    </div>
    <div class="pages">
        <ul class="pagination">
            <!--처음페이지-->
            <li class="page-item">
                <a class="page-link" href="?page=1">처음</a>
            </li>
            <!-- 이전페이지 -->
            {% if results.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ data.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in data.paginator.page_range %}
                {% if page_number >= data.number|add:-2 and page_number <= data.number|add:2 %}
                    {% if page_number == data.number %}
                    <li class="page-item-active">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if results.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ data.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
    </div>
{% endblock %}

AMproject/sub1app/templates/sub1app/searchRC.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'sub1app/searchRC.css' %}"  type='text/css'> 
    
{% endblock %}

{% block content %}
    <h2>구조센터 찾기</h2>
    <form actions="{% url 'sub1app:searchRC' %}" method = "POST">
        {% csrf_token %}
        <div class="options">
            <input type="checkbox" name="regions[]" value="전체" {% if '전체' in regions %}checked{% endif %}> 전체
            <input type="checkbox" name="regions[]" value="서울" {% if '서울' in regions %}checked{% endif %}> 서울
            <input type="checkbox" name="regions[]" value="부산" {% if '부산' in regions %}checked{% endif %}> 부산
            <input type="checkbox" name="regions[]" value="광주" {% if '광주' in regions %}checked{% endif %}> 광주
            <input type="checkbox" name="regions[]" value="대전" {% if '대전' in regions %}checked{% endif %}> 대전
            <input type="checkbox" name="regions[]" value="울산" {% if '울산' in regions %}checked{% endif %}> 울산<br> 
            <input type="checkbox" name="regions[]" value="인천" {% if '인천' in regions %}checked{% endif %}> 인천
            <input type="checkbox" name="regions[]" value="대구" {% if '대구' in regions %}checked{% endif %}> 대구

            <input type="checkbox" name="regions[]" value="경기" {% if '경기' in regions %}checked{% endif %}> 경기
            <input type="checkbox" name="regions[]" value="강원" {% if '강원' in regions %}checked{% endif %}> 강원
            <input type="checkbox" name="regions[]" value="충북" {% if '충북' in regions %}checked{% endif %}> 충북
            <input type="checkbox" name="regions[]" value="충남" {% if '충남' in regions %}checked{% endif %}> 충남<br>
            <input type="checkbox" name="regions[]" value="전북" {% if '전북' in regions %}checked{% endif %}> 전북
            <input type="checkbox" name="regions[]" value="전남" {% if '전남' in regions %}checked{% endif %}> 전남
            <input type="checkbox" name="regions[]" value="경북" {% if '경북' in regions %}checked{% endif %}> 경북
            <input type="checkbox" name="regions[]" value="경남" {% if '경남' in regions %}checked{% endif %}> 경남
            <input type="checkbox" name="regions[]" value="제주" {% if '제주' in regions %}checked{% endif %}> 제주
            
            <button id="searchbtn" type = "submit">검색</button>
        </div>
    </form>    
    <div class="list_RC">
        <table class="data_table">
            <thead>
            <tr>
                <td style="width: 50px;"><B>번호</B></td>
                <td><B>센터명</B></td>
                <td><B>주소</B></td>
                <td><B>전화번호</B></td>
            </tr>
            </thead>
            <tbody>
            {% for data in results %}
            <tr>
                <td><span class="linum">{{ data.pk }}</span>번</td>
                <td class="link"><a href="{% url 'sub1app:center_info' data.pk %}">{{ data.name }} </a></td>
                <td>{{ data.address_road}}</td>
                <td>{{ data.tel }}</td>
            </tr>
            {% empty %}
                데이터가 없습니다.
            {% endfor %}
            <tbody>
        </table>
    </div>
    <div class="pages">
        <ul class="pagination">
            <!--처음페이지-->
            <li class="page-item">
                <a class="page-link" href="?page=1">처음</a>
            </li>
            <!-- 이전페이지 -->
            {% if results.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ results.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in results.paginator.page_range %}
                {% if page_number >= results.number|add:-2 and page_number <= results.number|add:2 %}
                    {% if page_number == results.number %}
                    <li class="page-item-active">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if results.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ results.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
    </div>
    <script>
        var orilist = document.getElementsByClassName("linum");
        // console.log(orilist);
        for(var i = 0; i<orilist.length;i++ ){
            var ori =orilist.item(i).innerHTML;
            // console.log(ori);
            var newnum = ori - 95;
            document.getElementsByClassName("linum")[i].innerHTML = newnum;
        }
    </script>
{% endblock %}

AMproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>알동말동</title>
    <link rel="stylesheet" href="{% static 'base.css' %}" type="text/css">
    {% block style %}
    {% endblock %}
</head>
<body>
    <div id="top">
        <h3 id="title" ><a  href="{% url 'mainapp:main' %}">알동말동</a></h3>
    </div>
    <div id="middle">
        {% block content %}
        {% endblock %}
    </div>
    <div id='bottom'>
        project team 알동말동 이지원 박윤진<br>
        copyrightⓒ 2021 All rights reserved by 알동말동
    </div>    
</body>
</html>